ServerRoot /var/www
ServerName localhost
DocumentRoot /var/www/localhost/htdocs
ServerSignature Off
ServerTokens Prod
TraceEnable Off
Timeout 300
KeepAlive On
MaxKeepAliveRequests 30
KeepAliveTimeout 3
UseCanonicalName Off
AccessFileName .htaccess
HostnameLookups Off
Listen 80
Listen 8080
User www-data
Group www-data
PidFile "/tmp/httpd.pid"
Suexec Off
#Mutex default:/run/apache2

LoadModule mpm_event_module /usr/lib/apache2/modules/mod_mpm_event.so
LoadModule authn_core_module /usr/lib/apache2/modules/mod_authn_core.so
LoadModule authz_core_module /usr/lib/apache2/modules/mod_authz_core.so
#LoadModule log_config_module /usr/lib/apache2/modules/mod_log_config.so
LoadModule http2_module /usr/lib/apache2/modules/mod_http2.so
#LoadModule unixd_module /usr/lib/apache2/modules/mod_unixd.so

StartServers       1
ThreadsPerChild    10
MinSpareThreads    10
MaxSpareThreads    10
MaxRequestWorkers  20
MaxConnectionsPerChild 10000

<IfModule http2_module>
    H2MinWorkers        10
    H2MaxWorkers        20
    H2MaxSessionStreams 10

    Protocols    h2c http/1.1
    H2EarlyHints on
</IfModule>

<Directory />
    AllowOverride none
    Require all denied
</Directory>

<Directory "/var/www/localhost/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

LogLevel warn
ErrorLog /dev/stderr
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog /dev/stdout combined
